### ISSUE TITLE
開始時間と終了時間はあった方がいいかも。

### ISSUE THREAD

**Issue by talasago** [kiitok-study-group/Study_content#3]
開始時間にはやることを口頭で話すorプルリクで投げる場合、やったことを話せた方がやったことに対してのフィードバックがもらえたり、やったことを話すor書くことによってアウトプットの機会になる。

あと終了時間がないと抜けづらい人もいそう。終了時間を決めて、その後残る人は残る方がよさげでは。

**Comment by miriwo0104** [comment]
終了時間を22時設定したためcloseします
